# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.3 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================




prefix = /usr/local
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
INSTALL = /usr/bin/install -c
EXEEXT = 
WINDRES = 
SETFILE = 
STRIP = strip
NM = nm
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_DIR = $(INSTALL) -d
BK_DEPS = /home/leonti/proba/kitchen/bk-deps
srcdir = .
bindir = ${exec_prefix}/bin
datadir = ${datarootdir}
LIBS = 
LDFLAGS_GUI = 
CXX = g++
CXXFLAGS =  -I/opt/wx/2.8/lib/wx/include/gtk2-unicode-release-2.8 -I/opt/wx/2.8/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
CPPFLAGS = 
LDFLAGS =  -L/opt/wx/2.8/lib -pthread   -L/usr/lib64   -lwx_gtk2u-2.8 

### Variables: ###

DESTDIR = 
ESTESCOOK_CXXFLAGS = -I/usr/include/mysql -I/usr/local/include/mysql++ -Wall \
	$(CPPFLAGS) $(CXXFLAGS)
ESTESCOOK_OBJECTS =  \
	$(__estescook___win32rc) \
	estescook_settings.o \
	estescook_kitchenMain.o \
	estescook_wx_std.o \
	estescook_conn_set_panel.o \
	estescook_prog_set_panel.o \
	estescook_utils.o \
	estescook_threeorders.o \
	estescook_db_set_panel.o \
	estescook_kitchenApp.o

### Conditionally set variables: ###

#CXXC = $(CXX)
CXXC = $(BK_DEPS) $(CXX)
__estescook___mac_setfilecmd = @true
#__estescook___mac_setfilecmd = \
#	$(SETFILE) -t APPL estescook$(EXEEXT)
COND_PLATFORM_OS2_1___estescook___os2_emxbindcmd = $(NM) estescook$(EXEEXT) | \
	if grep -q pmwin.763 ; then emxbind -ep estescook$(EXEEXT) ; fi
#__estescook___os2_emxbindcmd = $(COND_PLATFORM_OS2_1___estescook___os2_emxbindcmd)
#__estescook___win32rc = estescook_resource_rc.o

### Targets: ###

all: estescook$(EXEEXT)

install: all install_estescook
	$(INSTALL_DIR) $(DESTDIR)$(datadir)
	for f in locale/pl/LC_MESSAGES/estescook.mo locale/es/LC_MESSAGES/estescook.mo locale/ru/LC_MESSAGES/estescook.mo; do \
	if test ! -d $(DESTDIR)$(datadir)/`dirname $$f` ; then \
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/`dirname $$f`; \
	fi; \
	$(INSTALL_DATA) share/$$f $(DESTDIR)$(datadir)/$$f; \
	done

uninstall: uninstall_estescook
	for f in locale/pl/LC_MESSAGES/estescook.mo locale/es/LC_MESSAGES/estescook.mo locale/ru/LC_MESSAGES/estescook.mo; do \
	rm -f $(DESTDIR)$(datadir)/$$f; \
	done

install-strip: install
	$(STRIP) $(DESTDIR)$(bindir)/estescook$(EXEEXT)

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f estescook$(EXEEXT)

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

estescook$(EXEEXT): $(ESTESCOOK_OBJECTS) $(__estescook___win32rc)
	$(CXX) -o $@ $(ESTESCOOK_OBJECTS) $(LDFLAGS)  $(LDFLAGS_GUI)  $(LIBS) -lmysqlpp -lmysqlclient
	
	$(__estescook___mac_setfilecmd)
	$(__estescook___os2_emxbindcmd)

install_estescook: 
	$(INSTALL_DIR) $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) estescook$(EXEEXT) $(DESTDIR)$(bindir)

uninstall_estescook: 
	rm -f $(DESTDIR)$(bindir)/estescook$(EXEEXT)

estescook_resource_rc.o: $(srcdir)/src/res/resource.rc
	$(WINDRES) -i$< -o$@  --include-dir /usr/include/mysql --include-dir /usr/local/include/mysql++

estescook_settings.o: $(srcdir)/src/settings.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/settings.cpp

estescook_kitchenMain.o: $(srcdir)/src/kitchenMain.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/kitchenMain.cpp

estescook_wx_std.o: $(srcdir)/src/wx_std.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/wx_std.cpp

estescook_conn_set_panel.o: $(srcdir)/src/conn_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/conn_set_panel.cpp

estescook_prog_set_panel.o: $(srcdir)/src/prog_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/prog_set_panel.cpp

estescook_utils.o: $(srcdir)/src/utils.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/utils.cpp

estescook_threeorders.o: $(srcdir)/src/threeorders.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/threeorders.cpp

estescook_db_set_panel.o: $(srcdir)/src/db_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/db_set_panel.cpp

estescook_kitchenApp.o: $(srcdir)/src/kitchenApp.cpp
	$(CXXC) -c -o $@ $(ESTESCOOK_CXXFLAGS) $(srcdir)/src/kitchenApp.cpp


# Include dependency info, if present:
-include .deps/*.d

.PHONY: all install uninstall clean distclean install_estescook uninstall_estescook
